### ISSUE TITLE
Print ffmpeg errors

### ISSUE THREAD

**Issue by binarykitchen** [m1guelpf/auto-subtitle#23]
For unknown reasons the ffmpeg command fails without telling me why:

```
$ auto_subtitle ./videomail_preview.webm -o subtitled/
```

prints following:

```
Extracting audio from videomail_preview...
Generating subtitles for videomail_preview... This might take a while.
Detected language: English
  0%|                                                                                                                                                                                            | 0/69 [00:11<?, ?frames/s]
Adding subtitles to videomail_preview...
Traceback (most recent call last):
  File "/Users/michaelheuberger/.pyenv/versions/3.10.4/bin/auto_subtitle", line 33, in <module>
    sys.exit(load_entry_point('auto-subtitle==1.0', 'console_scripts', 'auto_subtitle')())
  File "/Users/michaelheuberger/.pyenv/versions/3.10.4/lib/python3.10/site-packages/auto_subtitle/cli.py", line 61, in main
    stderr = ffmpeg.concat(
  File "/Users/michaelheuberger/.pyenv/versions/3.10.4/lib/python3.10/site-packages/ffmpeg/_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
```

On MacOS here, using python v3.10.4 installed via pyenv and using ffmpeg v5.1.2 - any clues? Thanks

**Comment by tommyct614** [comment]
Did you manage to solve this?

**Comment by binarykitchen** [comment]
no

**Comment by tommyct614** [comment]
It worked for me by adding '--output_srt true' as a second argument.

**Comment by binarykitchen** [comment]
Hmm, thanks mate but getting weirder errors now:
```
Traceback (most recent call last):
  File "/home/michael-heuberger/.pyenv/versions/3.11.1/bin/auto_subtitle", line 33, in <module>
    sys.exit(load_entry_point('auto-subtitle==1.0', 'console_scripts', 'auto_subtitle')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michael-heuberger/.pyenv/versions/3.11.1/lib/python3.11/site-packages/auto_subtitle/cli.py", line 60, in main

    ).output(out_path).run(quiet=True, overwrite_output=True)

stderr
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michael-heuberger/.pyenv/versions/3.11.1/lib/python3.11/site-packages/ffmpeg/_run.py", line 325, in run

    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

stderr
23:54:07.714 ERROR videomail.io@infernal.videomail.local:
  0%|          | 0/657 [00:21<?, ?frames/s]
    Traceback (most recent call last):
      File "/home/michael-heuberger/.pyenv/versions/3.11.1/bin/auto_subtitle", line 33, in <module>
        sys.exit(load_entry_point('auto-subtitle==1.0', 'console_scripts', 'auto_subtitle')())
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/michael-heuberger/.pyenv/versions/3.11.1/lib/python3.11/site-packages/auto_subtitle/cli.py", line 60, in main
        ).output(out_path).run(quiet=True, overwrite_output=True)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/michael-heuberger/.pyenv/versions/3.11.1/lib/python3.11/site-packages/ffmpeg/_run.py", line 325, in run
        raise Error('ffmpeg', out, err)
    ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
    
23:54:07.746 TRACE videomail.io@infernal.videomail.local: client.onEnd (no event)
23:54:07.758 TRACE videomail.io@infernal.videomail.local: Received POST on /client-error/?x-videomail-site-name=videomail.io, processing now ...
Sun, 05 Feb 2023 10:54:07 GMT express deprecated req.host: Use req.hostname instead at node_modules/lodash/lodash.js:4837:28
23:54:07.799  WARN videomail.io@infernal.videomail.local:
    Oh no, server error!
  0%|          | 0/657 [00:21<?, ?frames/s]
    Traceback (most recent call last):
      File "/home/michael-heuberger/.pyenv/versions/3.11.1/bin/auto_subtitle", line 33, in <module>
        sys.exit(load_entry_point('auto-subtitle==1.0', 'console_scripts', 'auto_subtitle')())
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/michael-heuberger/.pyenv/versions/3.11.1/lib/python3.11/site-packages/auto_subtitle/cli.py", line 60, in main
        ).output(out_path).run(quiet=True, overwrite_output=True)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/michael-heuberger/.pyenv/versions/3.11.1/lib/python3.11/site-packages/ffmpeg/_run.py", line 325, in run
        raise Error('ffmpeg', out, err)
    ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
    "
```

**Comment by binarykitchen** [comment]
And funnily I wasn't talking nor saying anything during recording but it picked Nyorsk for the detected language hmmm...

**Comment by tarasyyyk** [comment]
@binarykitchen You can edit source file **/Users/michaelheuberger/.pyenv/versions/3.10.4/lib/python3.10/site-packages/auto_subtitle/cli.py**, line **61** to get more verbose error output.

Or you can generate subtitle separately (with option `--srt_only true`) and then merge your video with this subtitle file: `ffmpeg -i video.mp4 -i subtitle.srt -c copy -c:s mov_text output_video.mp4`. Read more [here on Stackoverflow](https://stackoverflow.com/questions/8672809/use-ffmpeg-to-add-text-subtitles) about how to do it.
Actually with this `ffmpeg` command you [have more options](https://www.bannerbear.com/blog/how-to-add-subtitles-to-a-video-file-using-ffmpeg/) to add subtitles: you can add soft/hard subs, change color, font, etc.

**Comment by moonuel** [comment]
i got this error two different ways: 
1. i tried calling auto_subtitle on a .webm file, which I fixed by downloading the target video as a .mp4 instead. i don't know if .webm is supported but that's the default download type for youtube-dl, if you used that so you gotta specify the output by adding ```-f mp4``` to the youtube-dl call 
2. i tried calling auto_subtitle on a video with a title written in japanese. ffmpeg doesn't seem to like japanese characters so I just renamed the target video to something with only english characters, then that worked fine

**Comment by mockinbirdy** [comment]
> @binarykitchen You can edit source file **/Users/michaelheuberger/.pyenv/versions/3.10.4/lib/python3.10/site-packages/auto_subtitle/cli.py**, line **61** to get more verbose error output.
> 
> Or you can generate subtitle separately (with option `--srt_only true`) and then merge your video with this subtitle file: `ffmpeg -i video.mp4 -i subtitle.srt -c copy -c:s mov_text output_video.mp4`. Read more [here on Stackoverflow](https://stackoverflow.com/questions/8672809/use-ffmpeg-to-add-text-subtitles) about how to do it. Actually with this `ffmpeg` command you [have more options](https://www.bannerbear.com/blog/how-to-add-subtitles-to-a-video-file-using-ffmpeg/) to add subtitles: you can add soft/hard subs, change color, font, etc.

Can you tell me what should be the command to run it without ffmpeg cause the error cannot seem to be fixed. Because it still shows me the same error even when I try to generate subtitles separately. Thanks.

**Comment by Kavan27** [comment]
I fixed it by fixing the path, I had /videos/video.mp4 changed it to videos/video.mp4

**Comment by zaltinsoy** [comment]
https://github.com/m1guelpf/auto-subtitle/pull/89/
Version in this pull request solved my path related problem in Windows.
